name: reviewdog
on: [pull_request]
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: golangci-lint
      uses: docker://reviewdog/action-golangci-lint:v1.1.7
      with:
        github_token: ${{ secrets.github_token }}
        golangci_lint_flags: "--config=.golangci.yml"
        level: info

